ShoesReLife/ShoesReLife/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls'), name = 'index' ),
    path('user_auth/', include("django.contrib.auth.urls")),
    path('user_auth/', include("user_auth.urls")),
    path('feedback/',include('feedback.urls')),
]

ShoesReLife/feedback/urls.py
from django.urls import path, include, re_path
from .views import *
# provide app name
app_name = 'feedback'

urlpatterns = [
    path('', feedback_home, name ='feedback_home'),  
    path('review/',review_rate, name = "review_rate"),
]

ShoesReLife/pages/urls.py
from django.urls import path, include, re_path
from .views import *

# provide app name
app_name = 'pages'

urlpatterns = [
    path('', homepage_view, name='pages_home'),
    path('pricelist/',price_view, name = 'price_list'),
    # path('test/', test_view, name = 'test'),
    path('aboutus/', about_us_view, name='about_us'),
    path('contactus/', contact_us_view, name = 'contact_us'),   
]

ShoesReLife/user_auth/urls.py
from django.urls import path, include, re_path
from .views import *

# provide app name
app_name = 'user_auth'

urlpatterns = [
                path('', user_login, name='login'),
                path('authenticate_user/', authenticate_user, name='authenticate_user'),
                # path('show_user/',show_user,name = 'show_user'),
                path('register/',register_user, name = 'register'),
                path('logout/',logout_view,name = 'logout'),
]

ShoesReLife/feedback/models.py
from django.db import models
from django.utils import timezone
from django.contrib import admin
from django.contrib.auth.models import User
import datetime

# class Question(models.Model):
#     question_text = models.CharField(max_length=200)
#     pub_date = models.DateTimeField('date published')

#     def __str__(self):
#         return self.question_text

#     @admin.display(
#         boolean=True,
#         ordering='pub_date',
#         description='Published recently?',
#     )

#     def was_published_recently(self):
#         now = timezone.now()
#         return now - datetime.timedelta(days=1) <= self.pub_date <= now

# class Choice(models.Model):
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     choice_text = models.CharField(max_length=200)
#     votes = models.IntegerField(default=0)

#     def __str__(self):
#         return self.choice_text
    
class Review(models.Model):
    """
    class to create new model(review)
    allows user to create a review
    """
    user = models.ForeignKey(User, models.CASCADE)
    comment = models.TextField(max_length=250)
    rate = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

ShoesReLife/pages/models.py
from django.db import models

# Create your models here.

ShoesReLife/user_auth/models.py
from django.db import models

# Create your models here.

ShoesReLife/user_auth/forms.py
# information to create registration form found on https://ordinarycoders.com/blog/article/django-user-register-login-logout


from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
    """
    Class used to create form; used to register new user
    """
    email = forms.EmailField(required=True)

    class Meta:
        """
        meta fields used for the registration of new users
        """
        model = User
        fields = ('username','email','password1','password2')

    def save(self, commit = True):
        """
        method to commit new user to database
        """
        user = super(NewUserForm, self).save(commit = False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
        return user

ShoesReLife/feedback/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from django.contrib.auth.decorators import login_required
from .models import Review


# Views directing user to relevant page

def feedback_home(request):
    """
    function directs user to feedback home page
    """

    # create new list containing all objects in Review model
    feedback_list = Review.objects.all()

    return render(request, 'feedback/feedback_home.html', {'feedback_list': feedback_list})

# user must be loged in to provide review
@login_required(login_url='/user_auth/')
def review_rate(request):
    """
    function to create new review

    :return: directs user back to feedback home page (refresh)
    """

    # checks if users submitted review
    if request.method == "POST":
        comment = request.POST.get('comment')
        rate = request.POST.get('rating')
        user = request.user
        # create new review using class/model
        Review(user = user, comment = comment, rate = rate).save()

        return HttpResponseRedirect(reverse('feedback:feedback_home'))

ShoesReLife/pages/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Views used to direct user to relevant page

def homepage_view(request):
    """
    Function directs user to homepage
    """
    return render(request,'pages/index.html')

def about_us_view(request):
    """
    Function directs user to about us page
    """
    return render(request,'pages/about_us.html')

def price_view(request):
    """
    Function directs user to price list page
    """
    return render(request,'pages/price_list.html')

def contact_us_view(request):
    """
    Function directs user to contact us page
    """
    return render(request,'pages/contact_us.html')

# def test_view(request):
#     """
#     Function directs user to test page
#     """
#     return render(request,'pages/test.html')

ShoesReLife/user_auth/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from .forms import NewUserForm # import from forms.py
from django.contrib import messages
from django.urls import reverse

# Create your views here.

def user_login(request):
    return render(request, 'user_auth/login.html')

def authenticate_user(request):
    """
    Function is used to authenticate the user.

    :param request: data input from the website received via request

    :return: directs user to appropriate page (if user is not found == register new user page; if user authenticated == home page)
    """
    username = request.POST['username']
    password = request.POST['password1']
    user = authenticate(username=username, password=password)

    if user is None:
        return HttpResponseRedirect(reverse('user_auth:register'))
    else:
        login(request,user)
        return HttpResponseRedirect(reverse('pages:pages_home'))
    
# def show_user(request):
#     print(request.user.username)
#     return render(request, 'user_auth/user.html', {
#                                             "username": request.user.username,
#                                             "password": request.user.password
#                                             })

def register_user(request):
    """
    function creates new user

    :param request: data input from the website received via request

    :return: directs user to appropriate page (if user registration is successful == home page)

    """

    # checks if form is being posted 
    if request.method == 'POST':
        form = NewUserForm(request.POST)

        # checks if form is valid
        if form.is_valid():
            # saves new user
            user = form.save()
            # logs in new user
            authenticate_user(request)
            messages.success(request, 'Registration Successful')
            return redirect('pages:pages_home')
        else:
            messages.error(request, 'Unsuccessful Registration. Invalid Information')
    
    # if form has not been posted, return blank form
    else:
        form = NewUserForm()
        return render(request = request, template_name = 'user_auth/user_registration.html', context = {'register_form':form})
    
def logout_view(request):
    """
    Function logs out user
    """
    logout(request)

        

ShoesReLife/feedback/templates/base.html
<!-- base.html -->

{% load static %}

<!DOCTYPE html>

<html lang = 'eng'>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale = 1.0">
        <!-- import bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
        <!-- import bootstrap avatar icon -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-avatar@latest/dist/avatar.min.css" rel="stylesheet">
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

        <!-- allow pdf import -->
        <script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@2.7.570/build/pdf.min.js"></script>
        <!-- import stylesheet -->
        {% block head %}{% endblock %}
        <!-- import icons -->
       
    </head>

    <body>
      <div class = "row">
            {% if user.is_authenticated %}
            <!-- navbar 2 (user logged in) -->
            <nav class="navbar navbar-expand-lg navbar-light bg-light gradient-custom fixed-top">
              <!-- Container wrapper start -->
              <div class="container-fluid">
                  <!-- Toggle button start -->
                  <button
                    class="navbar-toggler"
                    type="button"
                    data-mdb-toggle="collapse"
                    data-mdb-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                  >
                    <i class="fas fa-bars"></i>
                  </button>
                  <!-- Toggle button end -->

                  <!-- Collapsible wrapper start -->
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Navbar brand -->
                    <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'pages:pages_home' %}">
                      <img
                        src="{% static 'pages/shop_logo.jpg' %}"
                        height="100"
                        alt="Company Logo"
                        loading="lazy"
                      />
                    </a>
                    <!-- Left links start -->
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 h3">
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'pages:about_us' %}">About Us</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'pages:price_list' %}">Price List</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'pages:contact_us' %}">Contact Us</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'feedback:feedback_home' %}">Feedback</a>
                      </li>
                    </ul>
                    <!-- Left links end -->
                    <!-- Right elements start -->
                    <div class = "navbar-nav">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownAccount" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img 
                          class="avatar avatar-32 bg-light rounded-circle text-white p-2"
                          src="https://raw.githubusercontent.com/twbs/icons/main/icons/person-fill.svg">
                      </a>
                      
                      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownAccount">
                        <h5>{{ user.get_username }}</h5>
                        <li class="nav-item dropdown">
                          <a class="dropdown-item" href="{% url 'user_auth:logout' %}">Logout</a>
                        </li>
                      </ul>
                      
                    </div>
                    <!-- Right elements end -->
                  </div>
                  <!-- Collapsible wrapper end -->
            

                
              </div>
              <!-- Container wrapper end -->
            </nav>

            {% else %}
                <!-- navbar 1 (user not logged in) -->
                <nav class="navbar navbar-expand-lg navbar-light bg-light gradient-custom fixed-top">
                    <!-- Container wrapper -->
                    <div class="container-fluid">
                      <!-- Toggle button -->
                      <button
                        class="navbar-toggler"
                        type="button"
                        data-mdb-toggle="collapse"
                        data-mdb-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                      >
                        <i class="fas fa-bars"></i>
                      </button>
                  
                      <!-- Collapsible wrapper -->
                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <!-- Navbar brand -->
                        <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'pages:pages_home' %}">
                          <img
                            src="{% static 'pages/shop_logo.jpg' %}"
                            height="100"
                            alt="Company Logo"
                            loading="lazy"
                          />
                        </a>
                        <!-- Left links -->
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0 h3">
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'pages:about_us' %}">About Us</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'pages:price_list' %}">Price List</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'pages:contact_us' %}">Contact Us</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'feedback:feedback_home' %}">Feedback</a>
                          </li>
                        </ul>
                        <!-- Left links -->
                      </div>
                      <!-- Collapsible wrapper -->
                  
                      <!-- Right elements -->
                      <div class="d-flex align-items-center">
                          <ul class="navbar-nav me-auto mb-2 mb-lg-0 navbar-dark">
                            <li class="nav-item">
                              <a class="nav-link" href="{% url 'user_auth:login' %}">Login</a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link" href="{% url 'user_auth:register' %}">Register</a>
                            </li>
                          </ul>
                        <!-- Avatar 
                        <div class="dropdown">
                          <a
                            class="dropdown-toggle d-flex align-items-center hidden-arrow"
                            href="#"
                            id="navbarDropdownMenuAvatar"
                            role="button"
                            data-mdb-toggle="dropdown"
                            aria-expanded="false"
                          >
                            <img
                              src="https://mdbcdn.b-cdn.net/img/new/avatars/2.webp"
                              class="rounded-circle"
                              height="25"
                              alt="Black and White Portrait of a Man"
                              loading="lazy"
                            />
                          </a>
                          <ul
                            class="dropdown-menu dropdown-menu-end"
                            aria-labelledby="navbarDropdownMenuAvatar"
                          >
                            <li>
                              <a class="dropdown-item" href="#">My profile</a>
                            </li>
                            <li>
                              <a class="dropdown-item" href="#">Settings</a>
                            </li>
                            <li>
                              <a class="dropdown-item" href="#">Logout</a>
                            </li>
                          </ul>
                        </div>-->
                      </div>
                      <!-- Right elements -->
                    </div>
                    <!-- Container wrapper -->
                  </nav>

              {% endif %}
      </div>
      <br><br><br><br><br><br>
      <div class = "row">
          {% block main %}{% endblock %}
      </div>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
      <!-- bootstrap icons -->
      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    </body>
</html>

ShoesReLife/pages/templates/pages/base.html
<!-- base.html -->

{% load static %}

<!DOCTYPE html>

<html lang = 'eng'>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale = 1.0">
        <!-- import bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
        <!-- import bootstrap avatar icon -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-avatar@latest/dist/avatar.min.css" rel="stylesheet">
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

        <!-- allow pdf import -->
        <script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@2.7.570/build/pdf.min.js"></script>
        <!-- import stylesheet -->
        <link rel = 'stylesheet'  href = "{% static 'stylesheet.css' %}">
        <!-- import icons -->

    </head>

    <body>
      <div class = "row">
            {% if user.is_authenticated %}
            <!-- navbar 2 (user logged in) -->
            <nav class="navbar navbar-expand-lg navbar-light bg-light gradient-custom fixed-top">
              <!-- Container wrapper start -->
              <div class="container-fluid">
                  <!-- Toggle button start -->
                  <button
                    class="navbar-toggler"
                    type="button"
                    data-mdb-toggle="collapse"
                    data-mdb-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                  >
                    <i class="fas fa-bars"></i>
                  </button>
                  <!-- Toggle button end -->

                  <!-- Collapsible wrapper start -->
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Navbar brand -->
                    <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'pages:pages_home' %}">
                      <img
                        src="{% static 'pages/shop_logo.jpg' %}"
                        height="100"
                        alt="Company Logo"
                        loading="lazy"
                      />
                    </a>
                    <!-- Left links start -->
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 h3">
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'pages:about_us' %}">About Us</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'pages:price_list' %}">Price List</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'pages:contact_us' %}">Contact Us</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'feedback:feedback_home' %}">Feedback</a>
                      </li>
                    </ul>
                    <!-- Left links end -->
                    <!-- Right elements start -->
                    <div class = "navbar-nav">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownAccount" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img 
                          class="avatar avatar-32 bg-light rounded-circle text-white p-2"
                          src="https://raw.githubusercontent.com/twbs/icons/main/icons/person-fill.svg">
                      </a>
                      
                      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownAccount">
                        <h5>{{ user.get_username }}</h5>
                        <li class="nav-item dropdown">
                          <a class="dropdown-item" href="{% url 'user_auth:logout' %}">Logout</a>
                        </li>
                      </ul>
                      
                    </div>
                    <!-- Right elements end -->
                  </div>
                  <!-- Collapsible wrapper end -->
            

                
              </div>
              <!-- Container wrapper end -->
            </nav>

            {% else %}
                <!-- navbar 1 (user not logged in) -->
                <nav class="navbar navbar-expand-lg navbar-light bg-light gradient-custom fixed-top">
                    <!-- Container wrapper -->
                    <div class="container-fluid">
                      <!-- Toggle button -->
                      <button
                        class="navbar-toggler"
                        type="button"
                        data-mdb-toggle="collapse"
                        data-mdb-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                      >
                        <i class="fas fa-bars"></i>
                      </button>
                  
                      <!-- Collapsible wrapper -->
                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <!-- Navbar brand -->
                        <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'pages:pages_home' %}">
                          <img
                            src="{% static 'pages/shop_logo.jpg' %}"
                            height="100"
                            alt="Company Logo"
                            loading="lazy"
                          />
                        </a>
                        <!-- Left links -->
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0 h3">
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'pages:about_us' %}">About Us</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'pages:price_list' %}">Price List</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'pages:contact_us' %}">Contact Us</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'feedback:feedback_home' %}">Feedback</a>
                          </li>
                        </ul>
                        <!-- Left links -->
                      </div>
                      <!-- Collapsible wrapper -->
                  
                      <!-- Right elements -->
                      <div class="d-flex align-items-center">
                          <ul class="navbar-nav me-auto mb-2 mb-lg-0 navbar-dark">
                            <li class="nav-item">
                              <a class="nav-link" href="{% url 'user_auth:login' %}">Login</a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link" href="{% url 'user_auth:register' %}">Register</a>
                            </li>
                          </ul>
                        <!-- Avatar 
                        <div class="dropdown">
                          <a
                            class="dropdown-toggle d-flex align-items-center hidden-arrow"
                            href="#"
                            id="navbarDropdownMenuAvatar"
                            role="button"
                            data-mdb-toggle="dropdown"
                            aria-expanded="false"
                          >
                            <img
                              src="https://mdbcdn.b-cdn.net/img/new/avatars/2.webp"
                              class="rounded-circle"
                              height="25"
                              alt="Black and White Portrait of a Man"
                              loading="lazy"
                            />
                          </a>
                          <ul
                            class="dropdown-menu dropdown-menu-end"
                            aria-labelledby="navbarDropdownMenuAvatar"
                          >
                            <li>
                              <a class="dropdown-item" href="#">My profile</a>
                            </li>
                            <li>
                              <a class="dropdown-item" href="#">Settings</a>
                            </li>
                            <li>
                              <a class="dropdown-item" href="#">Logout</a>
                            </li>
                          </ul>
                        </div>-->
                      </div>
                      <!-- Right elements -->
                    </div>
                    <!-- Container wrapper -->
                  </nav>

              {% endif %}
      </div>
      <br><br><br><br><br><br>
      <div class = "row">
          {% block main %}{% endblock %}
      </div>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
      <!-- bootstrap icons -->
      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    </body>
</html>

ShoesReLife/user_auth/templates/user_auth/login.html
{% extends "user_auth/base.html" %}

{% load static %}

{% block title %}Login Page{% endblock %}


{% block main %}
<div class = "row">
    <div class="col-lg-1"></div>
    <div class="col-lg-4 gradient-custom">
        <h3>Login</h3>
        <br>
        <form action="{% url 'user_auth:authenticate_user' %}" method = "POST">
            {% csrf_token %}
            <!-- Username input -->

            <input type="text" name="username" placeholder="User" required class = "form-control"/>
            <label class="form-label text-white" >Username</label>

          
            <!-- Password input -->

            <input type = "password" name = "password1" class = "form-control"/>
            <label class = "form-label text-white" >Password</label>

          
            <!-- 2 column grid layout for inline styling -->
          
                <!-- Submit button -->
            <div>
                <button type="submit" class="btn btn-primary btn-block mb-4" value = "Login">Sign in</button>
            </div>
          
                <!-- Register buttons -->
            <div class="text-center">
                <p>Not a member? <a href="{% url 'user_auth:register' %}">Register</a></p>
            </div>
        </form>
    </div>
    <div class="col-lg-5"></div>
</div>
<br>
<div class = 'row'></div><br>

{% endblock %}